concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "trump"
  url = "https://elinext-ai-gitlab.tech/"
  #clone_url = "http://192.168.1.3"
  id = 3
  token = "glrt-agJ5yZ188vhm4_wH8KyRfm86MQpwOjEKdDozCnU6MQ8.01.170javfu1"
  token_obtained_at = 2025-12-08T15:10:37Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "ruby:3.3"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"] 
    shm_size = 0
    network_mtu = 0
    extra_hosts = ["elinext-ai-gitlab.tech:192.168.1.3"]
